#pragma once

#include "driver/gpio.h"

#define APP_NAME "xiaozhi_chatbox"
#define APP_VERSION "0.1.0"

#define BOARD_STATUS_LED_GPIO GPIO_NUM_8
#define BOARD_STATUS_LED_ACTIVE_LEVEL 1

#define BOARD_BOOT_BUTTON_GPIO GPIO_NUM_0
#define BOARD_BOOT_BUTTON_ACTIVE_LEVEL 0
#define BOARD_BOOT_BUTTON_DEBOUNCE_MS 50

#define BOARD_OLED_I2C_PORT I2C_NUM_0
#define BOARD_OLED_I2C_SDA_GPIO GPIO_NUM_47
#define BOARD_OLED_I2C_SCL_GPIO GPIO_NUM_21
#define BOARD_OLED_I2C_ADDRESS 0x3C
#define BOARD_OLED_I2C_FREQ_HZ 400000
#define BOARD_OLED_WIDTH 128
#define BOARD_OLED_HEIGHT 32

#define BOARD_COMPASS_UART_PORT UART_NUM_1
#define BOARD_COMPASS_UART_RX_GPIO GPIO_NUM_18
#define BOARD_COMPASS_UART_TX_GPIO GPIO_NUM_17
#define BOARD_COMPASS_UART_BAUD_RATE 115200
#define BOARD_COMPASS_LED_ON_THRESHOLD_DECI_DEG 320
#define BOARD_COMPASS_LED_OFF_THRESHOLD_DECI_DEG 280
#define BOARD_COMPASS_DEADBAND_DECI_DEG 20
#define BOARD_COMPASS_STARTUP_SAMPLES 16
#define BOARD_COMPASS_FILTER_SHIFT 3
#define BOARD_COMPASS_POLL_INTERVAL_MS 100
#define BOARD_COMPASS_ZERO_ON_STARTUP 1

#define BOARD_MPU6050_I2C_ADDRESS 0x68
#define BOARD_MPU6050_POLL_INTERVAL_MS 100
#define BOARD_MPU6050_STARTUP_SAMPLES 32
#define BOARD_MPU6050_FILTER_SHIFT 2
#define BOARD_MPU6050_LED_ON_THRESHOLD_DEG 30.0f
#define BOARD_MPU6050_LED_OFF_THRESHOLD_DEG 27.0f

#define BOARD_PS2_CLK_GPIO GPIO_NUM_14
#define BOARD_PS2_CMD_GPIO GPIO_NUM_13
#define BOARD_PS2_ATT_GPIO GPIO_NUM_12
#define BOARD_PS2_DAT_GPIO GPIO_NUM_11
#define BOARD_PS2_CLOCK_DELAY_US 12
#define BOARD_PS2_POLL_INTERVAL_MS 50
#define BOARD_PS2_STICK_DEADZONE 35

#ifndef WIFI_SSID
#define WIFI_SSID ""
#endif

#ifndef WIFI_PASSWORD
#define WIFI_PASSWORD ""
#endif

#ifndef XIAOZHI_SERVER_URL
#define XIAOZHI_SERVER_URL "wss://api.tenclass.net/xiaozhi/v1/"
#endif

#define XIAOZHI_APP_TASK_STACK_SIZE 4096
#define XIAOZHI_APP_TASK_PRIORITY 5
